name: 存储桶同步
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: 安装coscmd
      run: sudo pip install coscmd
    - name: 配置coscmd
      env:
        SECRET_ID: ${{ secrets.COS_SECRET_ID }}
        SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
        BUCKET: qlulife-1309278520
        REGION: ap-shanghai
      run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
    - name: 上传
      run: coscmd upload -rs --delete -f ./ / --ignore "./.git/*"
    - name: 打开脚本目录
      run: cd scripts/cdn-refresher
    - name: 刷新CDN缓存
      run: npm install qcloud-cdn-node-sdk && npm run qcloudcdn